# Generated by Django 4.0.5 on 2022-07-04 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('study', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='students/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Outside Students',
            },
        ),
    ]
