# Generated by Django 4.0.5 on 2022-07-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outsidestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='outside_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.outsidestudent'),
        ),
    ]
